version: '2'
services:
    jenkins.docker:
        image: rbcjenkins
        ports:
            - "8080:8080"
        volumes:
            - ./jenkins_home:/data/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
